export const FETCH_HOME_FEED = 'FETCH_HOME_FEED';
export const FETCH_HOME_FEED_SUCCESS = 'FETCH_HOME_FEED_SUCCESS';
export const FETCH_HOME_FEED_FAIL = 'FETCH_HOME_FEED_FAIL';

export const FETCH_FILTER_CATEGORY_LIST = 'FETCH_FILTER_CATEGORY_LIST';
export const FETCH_FILTER_CATEGORY_LIST_SUCCESS = 'FETCH_FILTER_CATEGORY_LIST_SUCCESS';
export const FETCH_FILTER_CATEGORY_LIST_FAIL = 'FETCH_FILTER_CATEGORY_LIST_FAIL';
